version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - VITE_BACKEND_BASE_URI=http://localhost:3001/feed
    depends_on:
      - backend
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/feed-db
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: